// Finora contextual help — task-oriented guidance embedded in operational screens.
(function(){
 const GUIDES={
  accounts:{title:'راهنمای کدینگ حسابداری',html:'<p><b>اصل:</b> حساب کل برای گزارش سطح بالا، معین برای تفکیک و حساب ثبت‌پذیر برای آرتیکل است. طرف‌حساب، پروژه و قرارداد را با ساختن حساب جداگانه تکثیر نکنید؛ آن‌ها تفصیلی/بعد تحلیلی هستند.</p><ol><li>قالب پیشنهادی متناسب با فعالیت شرکت را مبنا قرار دهید.</li><li>برای حساب ثبت‌پذیر، ماهیت و نقش سیستمی را فقط وقتی مشخص کنید که کاربرد آن روشن است.</li><li>حسابی که سابقه دفتر دارد حذف یا بازساخت نمی‌شود؛ برای حفظ تاریخچه غیرفعال می‌شود.</li></ol>'},
  dimensions:{title:'راهنمای تفصیلی شناور',html:'<p>تفصیلی شناور یک بُعد مستقل مثل طرف‌حساب، پروژه، قرارداد یا مرکز هزینه است.</p><ol><li>کد را سیستم خودکار می‌سازد؛ کد دستی وارد نمی‌کنید.</li><li>برای اشخاص/پروژه/شعب/قرارداد از منبع متصل استفاده کنید تا داده پایه تکرار نشود.</li><li>تفصیلی دستی فقط برای دسته‌ای است که داده پایه مستقل ندارد و مقدارهایش هم کد ترتیبی خودکار می‌گیرند.</li><li>در قواعد تفصیلی مشخص کنید هر حساب کدام بُعد را الزامی، اختیاری یا غیرمجاز می‌داند.</li></ol>'},
  products:{title:'راهنمای کدینگ کالا و خدمت',html:'<p>کد داخلی کالا همان <b>کد کالا</b> است و در سند الکترونیکی نیز شناسه داخلی محسوب می‌شود. شناسه سامانه مالیاتی/خارجی مستقل است.</p><p>کالای جدید کد شش‌رقمی می‌گیرد: <b>یک رقم گروه اصلی + یک رقم زیرگروه + چهار رقم توالی</b>. مثال گروه ۱، زیرگروه ۱، اولین کالا: ۱۱۰۰۰۱. کد تاریخی موجود تغییر نمی‌کند.</p><p>انتخاب کالا روی کد، نام، مشخصه، بارکد، گروه، زیرگروه و شناسه خارجی جستجو می‌کند.</p>'},
  invoices:{title:'راهنمای اسناد تجاری',html:'<p>«فاکتورها» یک فضای ثابت دارد. نوع سند را فقط از انتخابگر اصلی فروش، خرید، پیش‌فاکتور فروش یا صورت‌وضعیت فروش تعیین کنید.</p><p>با تغییر نوع سند، نقش طرف حساب، انبار، قیمت پیش‌فرض و قواعد حسابداری تغییر می‌کند؛ جای کنترل‌های اصلی ثابت می‌ماند. فروش از قیمت فروش و خرید از قیمت خرید استفاده می‌کند.</p>'},
  contacts:{title:'راهنمای اشخاص و طرف‌حساب‌ها',html:'<p>هر شخص فقط یک‌بار در اطلاعات پایه ساخته می‌شود و می‌تواند مشتری، تأمین‌کننده یا هر دو باشد. برای یک شخص حساب‌های جداگانه نسازید؛ سیستم همان هویت را با حساب کنترل مناسب استفاده می‌کند.</p><p>برای پیدا کردن شخص، بخشی از نام، کد، موبایل یا شناسه ثبت‌شده را در همان کنترل انتخاب تایپ کنید.</p>'},
  journal:{title:'راهنمای سند حسابداری',html:'<p>ثبت دستی سند حسابداری برای رویدادهای استثنایی است؛ فروش، خرید، دریافت و پرداخت باید از عملیات خودشان سند خودکار بسازند.</p><ol><li>تاریخ و شرح مرجع را ثبت کنید.</li><li>حساب را انتخاب کنید و فقط ابعادی را تکمیل کنید که قاعده حساب لازم می‌داند.</li><li>جمع بدهکار و بستانکار باید برابر باشد.</li><li>سند قطعی آزادانه حذف یا ویرایش نمی‌شود؛ اصلاح با برگشت/سند اصلاحی انجام می‌شود.</li></ol>'},
  treasury:{title:'راهنمای خزانه‌داری',html:'<p>دریافت و پرداخت را با جهت واقعی جریان وجه ثبت کنید و در صورت ارتباط، آن را به فاکتور نسیه تخصیص دهید. مانده طرف‌حساب باید از سند حسابداری و تخصیص‌های معتبر قابل ردیابی باشد.</p><p>چک، حساب بانکی و صندوق ابزار تسویه‌اند؛ ثبت آن‌ها نباید جای سند تجاری یا هزینه/درآمد را بگیرد.</p>'},
  projects:{title:'راهنمای پروژه‌ها و قراردادها',html:'<p>پروژه یک داده پایه سراسری شرکت است، نه زیررکورد تکراری هر شخص. یک پروژه موجود را به طرف‌حساب مرتبط کنید یا یک پروژه جدید بسازید؛ همان پروژه در اسناد و تفصیلی پروژه قابل استفاده است.</p>'},
  settings:{title:'راهنمای تنظیمات',html:'<p>تنظیمات روی شرکت فعال و حساب کاربری اثر می‌گذارد. قبل از عملیات بازگشت کارخانه پشتیبان بگیرید. بازگشت کارخانه داده‌های عملیاتی شرکت فعال را پاک می‌کند ولی خود شرکت و حساب ورود را نگه می‌دارد.</p><p>مدیر سیستم می‌تواند ظرفیت لایسنس و کاربران را مدیریت کند. تغییر رمز شخصی از بخش حساب کاربری انجام می‌شود.</p>'}
 };
 window.finoraShowGuide=function(key){const g=GUIDES[key]||GUIDES.accounts,old=document.getElementById('finora-context-guide');if(old)old.remove();const m=document.createElement('div');m.id='finora-context-guide';m.className='modal-backdrop active';m.innerHTML='<div class="modal-card" style="max-width:720px;line-height:2"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><h3>'+g.title+'</h3><button type="button" class="btn btn-secondary btn-inline" onclick="this.closest(\'.modal-backdrop\').remove()">بستن</button></div><div style="margin-top:12px">'+g.html+'</div></div>';document.body.appendChild(m)};
 const VIEW_GUIDES={'view-contacts':'contacts','view-journal':'journal','view-payments':'treasury','view-cheques':'treasury','view-projects':'projects','view-settings':'settings','view-data-center':'settings'};
 function installGuideButtons(){for(const [viewId,key] of Object.entries(VIEW_GUIDES)){const view=document.getElementById(viewId);if(!view||view.querySelector('.finora-context-help-btn'))continue;const heading=view.querySelector('h1,h2,h3');if(!heading)continue;const b=document.createElement('button');b.type='button';b.className='btn btn-secondary btn-inline finora-context-help-btn';b.textContent='؟ راهنما';b.style.marginInlineStart='8px';b.onclick=()=>finoraShowGuide(key);heading.insertAdjacentElement('afterend',b);}}
 document.addEventListener('DOMContentLoaded',installGuideButtons);setTimeout(installGuideButtons,0);new MutationObserver(()=>installGuideButtons()).observe(document.documentElement,{childList:true,subtree:true});window.finoraInstallGuideButtons=installGuideButtons;
})();
