/* Iran-first enterprise foundation: HR obligations, treasury and compliance registry. */
const FINORA_IR_RULES={
 endService:{id:'IR-LABOR-24',title:'مزایای پایان کار',source:'قانون کار ماده ۲۴'},
 leave:{id:'IR-LABOR-66',title:'ذخیره مرخصی',source:'قانون کار ماده ۶۶',carry:9},
 provision:{id:'IR-AS-04',title:'ذخایر و بدهی‌های احتمالی',source:'استاندارد حسابداری ایران ۴'},
 consolidation:{id:'IR-AS-39',title:'صورت‌های مالی تلفیقی',source:'استاندارد حسابداری ایران ۳۹'},
 revenue:{id:'IR-AS-43',title:'درآمد قرارداد با مشتریان',source:'استاندارد حسابداری ایران ۴۳',effectiveFrom:'1404-01-01'}
};
function entRows(k){return (datastore[k]||[]).filter(x=>x.ownerUserId===currentUser?.id)}
function entCid(){const c=getMyCompanies(),s=getMySettings();return s.default_company_id||c[0]?.id||''}
function entId(p){return p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,7)}
function entMoney(v){return Number(v||0).toLocaleString('fa-IR')}
function ensureEnterpriseView(){let r=document.getElementById('view-enterprise');if(!r){r=document.createElement('section');r.id='view-enterprise';r.className='view-pane';document.querySelector('.main-surface')?.appendChild(r)}return r}
function enterpriseEndServiceEstimate(c){const s=new Date(c.startDate),e=c.endDate?new Date(c.endDate):new Date();if(!isFinite(s)||!isFinite(e)||e<s)return 0;return Math.max(0,Math.round(Number(c.lastMonthlyWage||0)*((e-s)/31557600000)))}
function enterpriseRender(task='employees'){
 const r=ensureEnterpriseView(),cid=entCid(),emps=entRows('employees').filter(x=>x.companyId===cid),contracts=entRows('employmentContracts').filter(x=>x.companyId===cid),leaves=entRows('employeeLeave').filter(x=>x.companyId===cid),cash=entRows('cashboxes').filter(x=>x.companyId===cid),petty=entRows('pettyCashFunds').filter(x=>x.companyId===cid);
 const eo='<option value="">— انتخاب کارکن —</option>'+emps.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.personnelNo+' · '+x.fullName)+'</option>').join('');
 const views={
 employees:`<div class="card"><h2>پرونده کارکنان</h2><p class="af-hint">هویت پرسنلی مستقل از حساب کاربری است و سابقه استفاده‌شده حذف نمی‌شود.</p><div class="form-row"><div class="form-group"><label>شماره پرسنلی</label><input id="ent-emp-no" class="form-control"></div><div class="form-group"><label>نام و نام خانوادگی</label><input id="ent-emp-name" class="form-control"></div><div class="form-group"><label>کد ملی</label><input id="ent-emp-national" class="form-control"></div><div class="form-group"><label>شروع همکاری</label><input id="ent-emp-start" class="form-control" placeholder="YYYY-MM-DD"></div></div><button class="btn" onclick="enterpriseSaveEmployee()">ثبت کارکن</button></div><div class="card"><div class="table-responsive"><table><thead><tr><th>پرسنلی</th><th>نام</th><th>کد ملی</th><th>شروع</th></tr></thead><tbody>${emps.map(x=>'<tr><td>'+esc(x.personnelNo)+'</td><td>'+esc(x.fullName)+'</td><td>'+esc(x.nationalId||'—')+'</td><td>'+esc(x.startDate||'—')+'</td></tr>').join('')||'<tr><td colspan="4">رکوردی نیست.</td></tr>'}</tbody></table></div></div>`,
 contracts:`<div class="card"><h2>قرارداد کار و تعهد پایان کار</h2><p class="af-hint">برآورد کنترلی بر مبنای ماده ۲۴؛ تسویه نهایی تابع وضعیت و مقررات مؤثر تاریخ تسویه است.</p><div class="form-row"><div class="form-group"><label>کارکن</label><select id="ent-contract-emp" class="form-control">${eo}</select></div><div class="form-group"><label>نوع قرارداد</label><select id="ent-contract-type" class="form-control"><option value="fixed">مدت معین</option><option value="indefinite">دائم</option><option value="project">کار معین</option></select></div><div class="form-group"><label>شروع</label><input id="ent-contract-start" class="form-control"></div><div class="form-group"><label>پایان</label><input id="ent-contract-end" class="form-control"></div><div class="form-group"><label>آخرین مزد ماهانه مبنا</label><input id="ent-contract-wage" class="form-control" type="number" min="0"></div></div><button class="btn" onclick="enterpriseSaveContract()">ثبت قرارداد</button></div><div class="card"><div class="table-responsive"><table><thead><tr><th>کارکن</th><th>دوره</th><th>مزد مبنا</th><th>برآورد پایان‌کار</th><th>نسخه قاعده</th></tr></thead><tbody>${contracts.map(x=>'<tr><td>'+esc(emps.find(e=>e.id===x.employeeId)?.fullName||'—')+'</td><td>'+esc(x.startDate)+' تا '+esc(x.endDate||'جاری')+'</td><td>'+entMoney(x.lastMonthlyWage)+'</td><td><strong>'+entMoney(enterpriseEndServiceEstimate(x))+'</strong></td><td>'+esc(x.ruleVersion)+'</td></tr>').join('')||'<tr><td colspan="5">قراردادی نیست.</td></tr>'}</tbody></table></div></div>`,
 leave:`<div class="card"><h2>مرخصی و انتقال مانده</h2><p class="af-hint">مانده سال، مصرف و انتقال جداست؛ کنترل ماده ۶۶ انتقال را حداکثر ۹ روز می‌گیرد.</p><div class="form-row"><div class="form-group"><label>کارکن</label><select id="ent-leave-emp" class="form-control">${eo}</select></div><div class="form-group"><label>سال</label><input id="ent-leave-year" class="form-control"></div><div class="form-group"><label>استحقاق (روز)</label><input id="ent-leave-earned" type="number" min="0" step=".5" class="form-control"></div><div class="form-group"><label>استفاده (روز)</label><input id="ent-leave-used" type="number" min="0" step=".5" class="form-control"></div></div><button class="btn" onclick="enterpriseSaveLeave()">ثبت/محاسبه</button></div><div class="card"><div class="table-responsive"><table><thead><tr><th>کارکن</th><th>سال</th><th>مانده</th><th>قابل انتقال</th></tr></thead><tbody>${leaves.map(x=>'<tr><td>'+esc(emps.find(e=>e.id===x.employeeId)?.fullName||'—')+'</td><td>'+esc(x.year)+'</td><td>'+x.remainingDays+'</td><td><strong>'+x.carryForwardDays+'</strong></td></tr>').join('')||'<tr><td colspan="4">رکوردی نیست.</td></tr>'}</tbody></table></div></div>`,
 treasury:`<div class="card"><h2>صندوق و تنخواه</h2><div class="form-row"><div class="form-group"><label>کد صندوق</label><input id="ent-cash-code" class="form-control"></div><div class="form-group"><label>عنوان</label><input id="ent-cash-title" class="form-control"></div><div class="form-group"><label>نوع</label><select id="ent-cash-type" class="form-control"><option value="rial">ریالی</option><option value="foreign">ارزی</option><option value="branch">شعبه</option></select></div><div class="form-group"><label>ارز</label><input id="ent-cash-currency" class="form-control" value="IRR"></div></div><button class="btn" onclick="enterpriseSaveCashbox()">ثبت صندوق</button><hr style="margin:18px 0"><div class="form-row"><div class="form-group"><label>عنوان تنخواه</label><input id="ent-petty-title" class="form-control"></div><div class="form-group"><label>تنخواه‌گردان</label><input id="ent-petty-custodian" class="form-control"></div><div class="form-group"><label>سقف مصوب</label><input id="ent-petty-limit" type="number" min="0" class="form-control"></div></div><button class="btn" onclick="enterpriseSavePetty()">ثبت تنخواه</button></div><div class="card"><div class="table-responsive"><table><thead><tr><th>نوع</th><th>عنوان</th><th>ارز/گرداننده</th><th>سقف</th></tr></thead><tbody>${cash.map(x=>'<tr><td>صندوق</td><td>'+esc(x.code+' · '+x.title)+'</td><td>'+esc(x.currency)+'</td><td>—</td></tr>').join('')}${petty.map(x=>'<tr><td>تنخواه</td><td>'+esc(x.title)+'</td><td>'+esc(x.custodian)+'</td><td>'+entMoney(x.approvedLimit)+'</td></tr>').join('')||'<tr><td colspan="4">رکوردی نیست.</td></tr>'}</tbody></table></div></div>`,
 compliance:`<div class="card"><h2>رجیستری انطباق ایران</h2><p class="af-hint">نرخ، سقف، معافیت و مهلت متغیر باید نسخه‌دار و تاریخ‌دار باشند؛ سند مالی نسخه قاعده استفاده‌شده را نگه می‌دارد.</p><div class="table-responsive"><table><thead><tr><th>شناسه</th><th>موضوع</th><th>منبع</th><th>تاریخ اثر</th></tr></thead><tbody>${Object.values(FINORA_IR_RULES).map(x=>'<tr><td>'+x.id+'</td><td>'+x.title+'</td><td>'+x.source+'</td><td>'+esc(x.effectiveFrom||'طبق نسخه مصوب')+'</td></tr>').join('')}</tbody></table></div></div>`
 };
 r.innerHTML='<div class="af-head"><div><h1>ERP سازمانی ایران</h1><p>منابع انسانی، تعهدات کارکنان، خزانه و کنترل انطباق</p></div></div>'+(views[task]||views.employees);
}
function enterpriseSaveEmployee(){if(!requireWrite())return;const no=document.getElementById('ent-emp-no')?.value.trim(),name=document.getElementById('ent-emp-name')?.value.trim();if(!no||!name)return alert('شماره پرسنلی و نام الزامی است.');if(entRows('employees').some(x=>x.companyId===entCid()&&x.personnelNo===no))return alert('شماره پرسنلی تکراری است.');datastore.employees.push({id:entId('EMP'),ownerUserId:currentUser.id,companyId:entCid(),personnelNo:no,fullName:name,nationalId:document.getElementById('ent-emp-national')?.value.trim()||'',startDate:document.getElementById('ent-emp-start')?.value.trim()||'',status:'active'});saveDatastore();enterpriseRender('employees')}
function enterpriseSaveContract(){if(!requireWrite())return;const employeeId=document.getElementById('ent-contract-emp')?.value,startDate=document.getElementById('ent-contract-start')?.value,lastMonthlyWage=Number(document.getElementById('ent-contract-wage')?.value||0);if(!employeeId||!startDate||lastMonthlyWage<=0)return alert('کارکن، شروع و مزد مبنا الزامی است.');datastore.employmentContracts.push({id:entId('EC'),ownerUserId:currentUser.id,companyId:entCid(),employeeId,contractType:document.getElementById('ent-contract-type')?.value||'fixed',startDate,endDate:document.getElementById('ent-contract-end')?.value||'',lastMonthlyWage,status:'active',ruleVersion:FINORA_IR_RULES.endService.id});saveDatastore();enterpriseRender('contracts')}
function enterpriseSaveLeave(){if(!requireWrite())return;const employeeId=document.getElementById('ent-leave-emp')?.value,year=document.getElementById('ent-leave-year')?.value.trim(),earnedDays=Number(document.getElementById('ent-leave-earned')?.value||0),usedDays=Number(document.getElementById('ent-leave-used')?.value||0);if(!employeeId||!year||earnedDays<0||usedDays<0)return alert('اطلاعات مرخصی معتبر نیست.');const remainingDays=Math.max(0,earnedDays-usedDays),carryForwardDays=Math.min(FINORA_IR_RULES.leave.carry,remainingDays),old=entRows('employeeLeave').find(x=>x.companyId===entCid()&&x.employeeId===employeeId&&x.year===year),row={ownerUserId:currentUser.id,companyId:entCid(),employeeId,year,earnedDays,usedDays,remainingDays,carryForwardDays,ruleVersion:FINORA_IR_RULES.leave.id};if(old)Object.assign(old,row);else datastore.employeeLeave.push({id:entId('LV'),...row});saveDatastore();enterpriseRender('leave')}
function enterpriseSaveCashbox(){if(!requireWrite())return;const code=document.getElementById('ent-cash-code')?.value.trim(),title=document.getElementById('ent-cash-title')?.value.trim();if(!code||!title)return alert('کد و عنوان صندوق الزامی است.');if(entRows('cashboxes').some(x=>x.companyId===entCid()&&String(x.code).toUpperCase()===code.toUpperCase()))return alert('کد صندوق تکراری است.');datastore.cashboxes.push({id:entId('CASH'),ownerUserId:currentUser.id,companyId:entCid(),code,title,type:document.getElementById('ent-cash-type')?.value||'rial',currency:(document.getElementById('ent-cash-currency')?.value||'IRR').toUpperCase(),status:'active'});saveDatastore();enterpriseRender('treasury')}
function enterpriseSavePetty(){if(!requireWrite())return;const title=document.getElementById('ent-petty-title')?.value.trim(),custodian=document.getElementById('ent-petty-custodian')?.value.trim(),approvedLimit=Number(document.getElementById('ent-petty-limit')?.value||0);if(!title||!custodian||approvedLimit<=0)return alert('عنوان، تنخواه‌گردان و سقف مصوب الزامی است.');datastore.pettyCashFunds.push({id:entId('PETTY'),ownerUserId:currentUser.id,companyId:entCid(),title,custodian,approvedLimit,status:'active'});saveDatastore();enterpriseRender('treasury')}
