/* Phase 3 — journal UI */
function ensureJournalView(){
 if(document.getElementById('view-journal'))return;const s=document.createElement('section');s.id='view-journal';s.className='view';s.innerHTML=`<div class="af-head"><div><h1>اسناد حسابداری</h1><p>ثبت دوبل، قطعی‌سازی، برگشت و تراز آزمایشی</p></div><span class="badge badge-info">فاز ۳</span></div>
 <div class="card"><h3>سند دستی</h3><div class="form-row"><div class="form-group"><label>تاریخ</label><input id="je-date" class="form-control"></div><div class="form-group"><label>شرح</label><input id="je-desc" class="form-control"></div></div><div id="je-lines"></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-secondary" onclick="jeAddRow()">＋ آرتیکل</button><button class="btn btn-success" onclick="jeSaveManual()">ثبت پیش‌نویس</button></div></div>
 <div class="card"><h3>دفتر اسناد</h3><div class="table-responsive"><table><thead><tr><th>شماره</th><th>تاریخ</th><th>شرح</th><th>وضعیت</th><th>بدهکار</th><th>بستانکار</th><th>عملیات</th></tr></thead><tbody id="je-vouchers"></tbody></table></div></div>
 <div class="card"><h3>تراز آزمایشی</h3><div class="table-responsive"><table><thead><tr><th>کد</th><th>حساب</th><th>بدهکار</th><th>بستانکار</th><th>مانده</th></tr></thead><tbody id="je-trial"></tbody></table></div></div>`;const main=document.querySelector('.main-surface'),p=document.getElementById('printable-invoice');p?main.insertBefore(s,p):main.appendChild(s);
}
function jeAddRow(){
 const box=document.getElementById('je-lines');if(!box)return;const row=document.createElement('div');row.className='form-row je-line';row.innerHTML='<div class="form-group"><label>حساب</label><select class="form-control je-account" onchange="jeRenderDims(this.closest(\'.je-line\'))"><option value="">انتخاب حساب</option>'+getMyAccounts().filter(x=>x.postingAllowed&&x.active!==false).map(x=>'<option value="'+x.id+'">'+esc(x.code)+' — '+esc(x.title)+'</option>').join('')+'</select></div><div class="form-group"><label>بدهکار</label><input class="form-control je-debit" inputmode="decimal"></div><div class="form-group"><label>بستانکار</label><input class="form-control je-credit" inputmode="decimal"></div><div class="form-group"><label>شرح</label><input class="form-control je-line-desc"></div><button class="btn btn-danger btn-inline" onclick="this.closest(\'.je-line\').remove()">×</button><div class="je-dims" style="width:100%"></div>';box.appendChild(row);
}
function jeRenderDims(row){
 const aid=row.querySelector('.je-account').value,box=row.querySelector('.je-dims'),rules=jeRulesForAccount(aid).filter(x=>x.applicability!=='unavailable');box.innerHTML=rules.map(r=>{const t=getMyDimensionTypes().find(x=>x.id===r.dimensionTypeId),vals=t?afResolvedValues(t).filter(v=>v.postable!==false):[];return t?'<label style="display:inline-block;margin:5px 8px">'+esc(t.title)+(r.applicability==='required'?' *':'')+' <select class="form-control je-dim" data-type="'+t.id+'" style="min-width:180px"><option value="">— انتخاب —</option>'+vals.map(v=>'<option value="'+v.id+'">'+esc(v.title||v.name)+'</option>').join('')+'</select></label>':''}).join('');
}
function jeCollectRows(){return[...document.querySelectorAll('#je-lines .je-line')].map(r=>({accountId:r.querySelector('.je-account').value,debit:parseFormattedNumber(r.querySelector('.je-debit').value),credit:parseFormattedNumber(r.querySelector('.je-credit').value),description:r.querySelector('.je-line-desc').value,dimensions:[...r.querySelectorAll('.je-dim')].filter(x=>x.value).map(x=>({dimensionTypeId:x.dataset.type,dimensionValueId:x.value}))}))}
function jeSaveManual(){try{const v=jeCreateDraft({date:document.getElementById('je-date').value||getJalaliNumeric(),description:document.getElementById('je-desc').value,lines:jeCollectRows()});alert('پیش‌نویس سند '+v.number+' ثبت شد.');renderJournal()}catch(e){alert(e.message)}}
function jePostUi(id){try{jePost(id);renderJournal()}catch(e){alert(e.message)}} function jeReverseUi(id){const why=prompt('علت برگشت سند:','اصلاح ثبت');if(why===null)return;try{jeReverse(id,getJalaliNumeric(),why);renderJournal()}catch(e){alert(e.message)}}
function jeDeleteUi(id){if(!confirm('پیش‌نویس حذف شود؟'))return;try{jeDeleteDraft(id);renderJournal()}catch(e){alert(e.message)}}
function renderJournal(){
 ensureJournalView();if(!currentUser)return;jeEnsureDefaultProfiles();const body=document.getElementById('je-vouchers'),vs=getMyJournalVouchers().slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));if(body)body.innerHTML=vs.length?vs.map(v=>'<tr><td>'+esc(v.number)+'</td><td>'+esc(v.date)+'</td><td>'+esc(v.description)+'</td><td>'+esc(v.status)+'</td><td>'+Number(v.totalDebit).toLocaleString('fa-IR')+'</td><td>'+Number(v.totalCredit).toLocaleString('fa-IR')+'</td><td>'+(v.status==='draft'?'<button class="btn btn-success btn-inline" onclick="jePostUi(\''+v.id+'\')">قطعی</button> <button class="btn btn-danger btn-inline" onclick="jeDeleteUi(\''+v.id+'\')">حذف</button>':v.status==='posted'?'<button class="btn btn-secondary btn-inline" onclick="jeReverseUi(\''+v.id+'\')">برگشت</button>':'—')+'</td></tr>').join(''):'<tr><td colspan="7" class="af-empty">سندی ثبت نشده است.</td></tr>';
 const tb=document.getElementById('je-trial'),rows=jeTrialBalance();if(tb)tb.innerHTML=rows.length?rows.map(x=>'<tr><td>'+esc(x.code)+'</td><td>'+esc(x.title)+'</td><td>'+x.debit.toLocaleString('fa-IR')+'</td><td>'+x.credit.toLocaleString('fa-IR')+'</td><td>'+x.balance.toLocaleString('fa-IR')+'</td></tr>').join(''):'<tr><td colspan="5" class="af-empty">گردشی وجود ندارد.</td></tr>';
 const d=document.getElementById('je-date');if(d&&!d.value)d.value=getJalaliNumeric();if(!document.querySelector('#je-lines .je-line')){jeAddRow();jeAddRow()}
}
document.addEventListener('DOMContentLoaded',ensureJournalView);
