/* Phase 3 / P0 — journal UI */
function ensureJournalView(){
 if(document.getElementById('view-journal'))return;const s=document.createElement('section');s.id='view-journal';s.className='view-pane';s.innerHTML=`<div class="af-head"><div><h1>اسناد حسابداری</h1><p>ثبت دوبل، ابعاد تحلیلی، قطعی‌سازی و برگشت اسناد</p></div></div>
 <div class="card" data-finora-task="new"><h3>ثبت سند حسابداری</h3><div class="form-row"><div class="form-group"><label>شماره سند</label><input id="je-number" class="form-control" placeholder="خودکار"></div><div class="form-group"><label>تاریخ</label><input id="je-date" class="form-control"></div><div class="form-group"><label>نوع سند</label><select id="je-voucher-type" class="form-control"><option value="manual">عادی</option><option value="adjustment">اصلاحی</option><option value="opening">افتتاحیه</option><option value="closing">اختتامیه</option></select></div><div class="form-group"><label>مرجع</label><input id="je-reference" class="form-control" placeholder="شماره فاکتور/قرارداد/نامه"></div></div>
 <div class="form-row"><div class="form-group" style="flex:1"><label>شرح سند</label><input id="je-desc" class="form-control"></div></div><div id="je-lines"></div>
 <div id="je-totals" class="af-hint" style="margin:10px 0;font-weight:700"></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-secondary" onclick="jeAddRow()">＋ آرتیکل</button><button class="btn btn-success" onclick="jeSaveManual()">ثبت پیش‌نویس</button></div></div>
 <div class="card" data-finora-task="register"><h3>فهرست اسناد حسابداری</h3><div class="table-responsive"><table><thead><tr><th>شماره</th><th>تاریخ</th><th>نوع</th><th>مرجع</th><th>شرح</th><th>وضعیت</th><th>بدهکار</th><th>بستانکار</th><th>منبع</th><th>عملیات</th></tr></thead><tbody id="je-vouchers"></tbody></table></div></div>
 <div class="card" data-finora-task="trial"><h3>تراز آزمایشی</h3><div class="table-responsive"><table><thead><tr><th>کد</th><th>حساب</th><th>بدهکار</th><th>بستانکار</th><th>مانده</th></tr></thead><tbody id="je-trial"></tbody></table></div></div>`;const main=document.querySelector('.main-surface'),p=document.getElementById('printable-invoice');p?main.insertBefore(s,p):main.appendChild(s);
}
function jeAccountOptions(){return getMyAccounts().filter(x=>x.postingAllowed&&x.active!==false).map(x=>'<option value="'+x.id+'">'+esc(x.code)+' — '+esc(x.title)+'</option>').join('')}
function jeAddRow(seed={}){
 const box=document.getElementById('je-lines');if(!box)return;const row=document.createElement('div');row.className='form-row je-line';row.innerHTML='<div class="form-group"><label>جستجوی حساب</label><input class="form-control je-account-search" placeholder="کد یا نام حساب" oninput="jeFilterAccounts(this)"><select class="form-control je-account" onchange="jeRenderDims(this.closest(\'.je-line\'))"><option value="">انتخاب حساب</option>'+jeAccountOptions()+'</select></div><div class="form-group"><label>بدهکار</label><input class="form-control je-debit" inputmode="decimal" oninput="jeUpdateTotals()"></div><div class="form-group"><label>بستانکار</label><input class="form-control je-credit" inputmode="decimal" oninput="jeUpdateTotals()"></div><div class="form-group"><label>شرح</label><input class="form-control je-line-desc"></div><div style="display:flex;gap:4px;align-items:end"><button type="button" class="btn btn-secondary btn-inline" title="کپی ردیف" onclick="jeCopyRow(this)">⧉</button><button type="button" class="btn btn-danger btn-inline" title="حذف ردیف" onclick="jeRemoveRow(this)">×</button></div><div class="je-dims" style="width:100%"></div>';box.appendChild(row);
 row.querySelector('.je-account').value=seed.accountId||'';row.querySelector('.je-debit').value=seed.debit||'';row.querySelector('.je-credit').value=seed.credit||'';row.querySelector('.je-line-desc').value=seed.description||'';jeRenderDims(row);(seed.dimensions||[]).forEach(d=>{const el=row.querySelector('.je-dim[data-type="'+d.dimensionTypeId+'"]');if(el)el.value=d.dimensionValueId||''});jeUpdateTotals();return row;
}
function jeFilterAccounts(input){const q=String(input.value||'').trim().toLowerCase(),sel=input.closest('.je-line')?.querySelector('.je-account');if(!sel)return;[...sel.options].forEach((o,i)=>{if(i===0){o.hidden=false;return}o.hidden=!!q&&!o.text.toLowerCase().includes(q)})}
function jeRenderDims(row){
 const aid=row.querySelector('.je-account').value,box=row.querySelector('.je-dims'),rules=jeRulesForAccount(aid).filter(x=>x.applicability!=='unavailable');box.innerHTML=rules.map(r=>{const t=getMyDimensionTypes().find(x=>x.id===r.dimensionTypeId),vals=t?afResolvedValues(t).filter(v=>v.postable!==false):[];return t?'<label style="display:inline-block;margin:5px 8px">'+esc(t.title)+(r.applicability==='required'?' *':'')+' <select class="form-control je-dim" data-type="'+t.id+'" style="min-width:180px"><option value="">— انتخاب —</option>'+vals.map(v=>'<option value="'+v.id+'">'+esc(v.title||v.name)+'</option>').join('')+'</select></label>':''}).join('');
}
function jeCollectRows(){return[...document.querySelectorAll('#je-lines .je-line')].map(r=>({accountId:r.querySelector('.je-account').value,debit:parseFormattedNumber(r.querySelector('.je-debit').value),credit:parseFormattedNumber(r.querySelector('.je-credit').value),description:r.querySelector('.je-line-desc').value,dimensions:[...r.querySelectorAll('.je-dim')].filter(x=>x.value).map(x=>({dimensionTypeId:x.dataset.type,dimensionValueId:x.value}))}))}
function jeUpdateTotals(){const rows=jeCollectRows(),d=rows.reduce((s,x)=>s+(Number(x.debit)||0),0),c=rows.reduce((s,x)=>s+(Number(x.credit)||0),0),diff=d-c,box=document.getElementById('je-totals');if(box)box.textContent='جمع بدهکار: '+d.toLocaleString('fa-IR')+' | جمع بستانکار: '+c.toLocaleString('fa-IR')+' | اختلاف: '+Math.abs(diff).toLocaleString('fa-IR')+(d>0&&Math.abs(diff)<0.0001?' ✓ تراز':'')}
function jeRemoveRow(btn){const rows=document.querySelectorAll('#je-lines .je-line');if(rows.length<=2)return alert('سند باید حداقل دو آرتیکل داشته باشد.');btn.closest('.je-line').remove();jeUpdateTotals()}
function jeCopyRow(btn){const row=btn.closest('.je-line'),seed={accountId:row.querySelector('.je-account').value,debit:row.querySelector('.je-debit').value,credit:row.querySelector('.je-credit').value,description:row.querySelector('.je-line-desc').value,dimensions:[...row.querySelectorAll('.je-dim')].filter(x=>x.value).map(x=>({dimensionTypeId:x.dataset.type,dimensionValueId:x.value}))};jeAddRow(seed)}
function jeClearManualForm(){['je-number','je-reference','je-desc'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});const box=document.getElementById('je-lines');if(box)box.innerHTML='';jeAddRow();jeAddRow();jeUpdateTotals()}
function jeSaveManual(){try{const v=jeCreateDraft({number:document.getElementById('je-number').value,date:document.getElementById('je-date').value||getJalaliNumeric(),voucherType:document.getElementById('je-voucher-type').value,reference:document.getElementById('je-reference').value,description:document.getElementById('je-desc').value,lines:jeCollectRows()});alert('پیش‌نویس سند '+v.number+' ثبت شد.');jeClearManualForm();renderJournal()}catch(e){alert(e.message)}}
function jePostUi(id){try{jePost(id);renderJournal()}catch(e){alert(e.message)}}
function jeReverseUi(id){const why=prompt('علت برگشت سند:','اصلاح ثبت');if(why===null)return;try{jeReverse(id,getJalaliNumeric(),why);renderJournal()}catch(e){alert(e.message)}}
function jeCopyVoucherUi(id){try{const v=jeCopyVoucherToDraft(id,getJalaliNumeric());alert('کپی سند به پیش‌نویس '+v.number+' ایجاد شد.');renderJournal()}catch(e){alert(e.message)}}
function jeDeleteUi(id){if(!confirm('پیش‌نویس حذف شود؟'))return;try{jeDeleteDraft(id);renderJournal()}catch(e){alert(e.message)}}
function jeStatusLabel(v){return v==='draft'?'پیش‌نویس':v==='posted'?'قطعی':v==='reversed'?'برگشت‌شده':v}
function jeTypeLabel(v){return({manual:'عادی',adjustment:'اصلاحی',opening:'افتتاحیه',closing:'اختتامیه',copy:'کپی',reversal:'برگشت'})[v]||v||'عادی'}
function renderJournal(){
 ensureJournalView();if(!currentUser)return;if(typeof afEnsureAccountingP0Compatibility==='function')afEnsureAccountingP0Compatibility();jeEnsureDefaultProfiles();const body=document.getElementById('je-vouchers'),vs=getMyJournalVouchers().slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));if(body)body.innerHTML=vs.length?vs.map(v=>'<tr><td>'+esc(v.number)+'</td><td>'+esc(v.date)+'</td><td>'+esc(jeTypeLabel(v.voucherType))+'</td><td>'+esc(v.reference||'—')+'</td><td>'+esc(v.description)+'</td><td>'+esc(jeStatusLabel(v.status))+'</td><td>'+Number(v.totalDebit).toLocaleString('fa-IR')+'</td><td>'+Number(v.totalCredit).toLocaleString('fa-IR')+'</td><td>'+esc(v.sourceType||'manual')+'</td><td>'+(v.status==='draft'?'<button class="btn btn-success btn-inline" onclick="jePostUi(\''+v.id+'\')">قطعی</button> <button class="btn btn-danger btn-inline" onclick="jeDeleteUi(\''+v.id+'\')">حذف</button> ':v.status==='posted'?'<button class="btn btn-secondary btn-inline" onclick="jeReverseUi(\''+v.id+'\')">برگشت</button> ':'')+'<button class="btn btn-secondary btn-inline" onclick="jeCopyVoucherUi(\''+v.id+'\')">کپی</button></td></tr>').join(''):'<tr><td colspan="10" class="af-empty">سندی ثبت نشده است.</td></tr>';
 const tb=document.getElementById('je-trial'),rows=jeTrialBalance();if(tb)tb.innerHTML=rows.length?rows.map(x=>'<tr><td>'+esc(x.code)+'</td><td>'+esc(x.title)+'</td><td>'+x.debit.toLocaleString('fa-IR')+'</td><td>'+x.credit.toLocaleString('fa-IR')+'</td><td>'+x.balance.toLocaleString('fa-IR')+'</td></tr>').join(''):'<tr><td colspan="5" class="af-empty">گردشی وجود ندارد.</td></tr>';
 const d=document.getElementById('je-date');if(d&&!d.value)d.value=getJalaliNumeric();if(!document.querySelector('#je-lines .je-line')){jeAddRow();jeAddRow()}jeUpdateTotals();
}
document.addEventListener('DOMContentLoaded',ensureJournalView);
