(function(){
let ec='',ep='',eq='',ee='';
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('fa-IR');
function btn(save,cancel,on,a,b){const s=$(save),c=$(cancel);if(s){s.innerHTML=on?b:a;s.className=on?'btn btn-primary':'btn btn-success';}if(c)c.style.display=on?'inline-flex':'none';}
function clr(ids){ids.forEach(id=>{if($(id))$(id).value='';});}

// طرف حساب
function resetContact(){ec='';clr(['contact-name-input','contact-mobile-input','contact-national-input','contact-economic-input','contact-reg-input','contact-postal-input','contact-address-input']);if($('contact-entity-type'))$('contact-entity-type').value='natural';if($('contact-role-input'))$('contact-role-input').value='customer';if($('contact-project-mode'))$('contact-project-mode').value='single';handleContactEntityChange();btn('contact-save-btn','contact-edit-cancel-btn',false,'➕ ثبت طرف حساب','💾 ذخیره اصلاحات');}
window.cancelContactEdit=resetContact;
window.editContact=function(id){const c=getMyContacts().find(x=>x.id===id);if(!c)return;ec=id;const v={'contact-entity-type':c.entity_type||'natural','contact-name-input':c.name||'','contact-role-input':c.role||'customer','contact-mobile-input':c.mobile||'','contact-national-input':c.national_id||'','contact-economic-input':c.economic_code||'','contact-reg-input':c.reg_number||'','contact-postal-input':c.postal_code||'','contact-address-input':c.address||'','contact-project-mode':c.project_mode||'single'};Object.keys(v).forEach(k=>{if($(k))$(k).value=v[k];});if(c.entity_type==='natural'&&$('contact-prefix-select'))$('contact-prefix-select').value=String(c.name||'').startsWith('فروشگاه')?'فروشگاه':'آقا/خانم';handleContactEntityChange();btn('contact-save-btn','contact-edit-cancel-btn',true,'','💾 ذخیره اصلاحات');$('contact-name-input')?.scrollIntoView({behavior:'smooth',block:'center'});};
window.commitSaveContact=function(){if(!requireWrite()||!currentUser)return;const type=$('contact-entity-type').value,raw=$('contact-name-input').value,prefix=type==='natural'?$('contact-prefix-select')?.value:'';if(!raw.trim()){alert('نام طرف حساب الزامی است.');return;}const p={entity_type:type,name:formatEntityName(raw,type,prefix),role:$('contact-role-input').value,mobile:$('contact-mobile-input').value||'',national_id:$('contact-national-input').value||'',economic_code:type==='natural'?'':$('contact-economic-input').value||'',reg_number:type==='natural'?'':$('contact-reg-input').value||'',postal_code:$('contact-postal-input').value||'',address:$('contact-address-input').value||'',project_mode:$('contact-project-mode').value||'single'};if(p.national_id&&getMyContacts().some(x=>x.id!==ec&&x.national_id===p.national_id)){alert('این شناسه/کد ملی قبلاً برای طرف حساب دیگری ثبت شده است.');return;}if(ec){const c=datastore.contacts.find(x=>x.id===ec&&x.ownerUserId===currentUser.id);if(!c)return;Object.assign(c,p);if(!Array.isArray(c.projects))c.projects=[];alert('طرف حساب اصلاح شد.');}else datastore.contacts.push({id:'C_'+Date.now(),ownerUserId:currentUser.id,...p,balance:0,projects:[]});saveDatastore();resetContact();refreshAllSurfaces();};
const dc=window.deleteContact;window.deleteContact=function(id){
  const sales=getMyInvoices().some(i=>i.contactId===id);
  const buys=(datastore.purchases||[]).some(p=>p.ownerUserId===currentUser?.id&&p.supplierId===id);
  const chqs=getMyCheques().some(q=>q.contactId===id);
  const pays=typeof getMyPayments==='function'&&getMyPayments().some(p=>p.contactId===id);
  if(sales||buys||chqs||pays){alert('این طرف حساب در اسناد مالی استفاده شده و برای حفظ سابقه قابل حذف نیست. ابتدا اسناد مرتبط را حذف یا به طرف حساب دیگری منتقل کنید.');return;}
  if(ec===id)resetContact();return dc(id);
};
const rc=window.renderContacts;window.renderContacts=function(){rc();document.querySelectorAll('#contacts-ledger-table-body tr').forEach(tr=>{const del=tr.querySelector('button.btn-danger');if(!del)return;const m=(del.getAttribute('onclick')||'').match(/deleteContact\('([^']+)'\)/);if(!m)return;const id=m[1],cell=del.parentElement;if(!cell.querySelector('.edit-contact')){const b=document.createElement('button');b.className='btn btn-secondary btn-inline edit-contact';b.style.cssText='padding:4px 8px;font-size:12px;min-height:30px;margin-left:5px';b.textContent='✏️ اصلاح';b.onclick=()=>editContact(id);cell.insertBefore(b,del);}});};

// کالا/خدمت
function resetProduct(){ep='';clr(['prod-code-input','prod-name-input','prod-spec-input','prod-internal-id-input','prod-category-input','prod-barcode-input']);if($('prod-type-input'))$('prod-type-input').value='good';if($('prod-min-stock-input'))$('prod-min-stock-input').value='0';if($('prod-unit-input'))$('prod-unit-input').value='عدد';if($('prod-buy-input'))$('prod-buy-input').value='0';if($('prod-sale-input'))$('prod-sale-input').value='0';btn('product-save-btn','product-edit-cancel-btn',false,'➕ ثبت کالا','💾 ذخیره اصلاحات');}
window.cancelProductEdit=resetProduct;
window.editProduct=function(id){const p=getMyProducts().find(x=>x.id===id);if(!p)return;ep=id;const v={'prod-code-input':p.code||'','prod-name-input':p.name||'','prod-spec-input':p.spec||'','prod-unit-input':p.unit||'عدد','prod-buy-input':fmt(p.buy_price),'prod-sale-input':fmt(p.sale_price),'prod-internal-id-input':p.internal_id||'','prod-type-input':p.type||'good','prod-category-input':p.category||'','prod-barcode-input':p.barcode||'','prod-min-stock-input':p.minStock||0};Object.keys(v).forEach(k=>{if($(k))$(k).value=v[k];});btn('product-save-btn','product-edit-cancel-btn',true,'','💾 ذخیره اصلاحات');};
window.commitSaveProduct=function(){if(!requireWrite()||!currentUser)return;const name=$('prod-name-input').value.trim();if(!name){alert('عنوان کالا الزامی است.');return;}const p={code:$('prod-code-input').value||String(getMyProducts().length+1),name,spec:$('prod-spec-input').value||'',unit:$('prod-unit-input').value||'عدد',buy_price:parseFormattedNumber($('prod-buy-input').value),sale_price:parseFormattedNumber($('prod-sale-input').value),internal_id:$('prod-internal-id-input').value||'',type:$('prod-type-input')?.value||'good',category:$('prod-category-input')?.value||'',barcode:$('prod-barcode-input')?.value||'',minStock:Math.max(0,parseFormattedNumber($('prod-min-stock-input')?.value||0))};if(getMyProducts().some(x=>x.id!==ep&&String(x.code||'')===String(p.code))){alert('کد کالا/خدمت تکراری است.');return;}if(ep){const x=datastore.products.find(x=>x.id===ep&&x.ownerUserId===currentUser.id);if(!x)return;Object.assign(x,p);alert('کالا/خدمت اصلاح شد.');}else datastore.products.push({id:'P_'+Date.now(),ownerUserId:currentUser.id,...p,stock:0});saveDatastore();resetProduct();refreshAllSurfaces();};
const dp=window.deleteProduct;window.deleteProduct=function(id){
  const sales=getMyInvoices().some(i=>(i.items||[]).some(it=>it.prodId===id));
  const buys=(datastore.purchases||[]).some(p=>p.ownerUserId===currentUser?.id&&(p.items||[]).some(it=>it.prodId===id));
  if(sales||buys){alert('این کالا/خدمت در فاکتور استفاده شده و برای حفظ سابقه قابل حذف نیست. ابتدا اسناد مرتبط را اصلاح یا حذف کنید.');return;}
  if(ep===id)resetProduct();return dp(id);
};
const rp=window.renderProducts;window.renderProducts=function(){rp();document.querySelectorAll('#products-catalog-table-body tr').forEach(tr=>{const del=tr.querySelector('button.btn-danger');if(!del)return;const m=(del.getAttribute('onclick')||'').match(/deleteProduct\('([^']+)'\)/);if(!m)return;const id=m[1],cell=del.parentElement;if(!cell.querySelector('.edit-product')){const b=document.createElement('button');b.className='btn btn-secondary btn-inline edit-product';b.style.cssText='padding:4px 8px;font-size:12px;min-height:30px;margin-left:5px';b.textContent='✏️ اصلاح';b.onclick=()=>editProduct(id);cell.insertBefore(b,del);}});};

// چک
function resetCheque(){eq='';clr(['chq-sayad-input','chq-bank-input','chq-amount-input','chq-due-input']);if($('chq-direction-input'))$('chq-direction-input').value='inbound';if($('chq-status-input'))$('chq-status-input').value='registered';btn('cheque-save-btn','cheque-edit-cancel-btn',false,'➕ ثبت چک','💾 ذخیره اصلاحات');}
window.cancelChequeEdit=resetCheque;
window.editCheque=function(id){const q=getMyCheques().find(x=>x.id===id);if(!q)return;if(q.status&&q.status!=='registered')return alert('چک تعیین‌تکلیف‌شده قابل بازنویسی نیست؛ اصلاح باید با رویداد/رکورد اصلاحی انجام شود.');eq=id;const v={'chq-direction-input':q.direction||'inbound','chq-contact-select':q.contactId||'','chq-sayad-input':q.sayad_id||'','chq-bank-input':q.bank||'','chq-amount-input':fmt(q.amount),'chq-due-input':q.due_date||'','chq-status-input':q.status||'registered'};Object.keys(v).forEach(k=>{if($(k))$(k).value=v[k];});btn('cheque-save-btn','cheque-edit-cancel-btn',true,'','💾 ذخیره اصلاحات');switchView('view-cheques');};
window.commitSaveCheque=function(){if(!requireWrite()||!currentUser)return;const s=$('chq-contact-select'),amount=parseFormattedNumber($('chq-amount-input').value),sayad=$('chq-sayad-input').value.trim();if(!sayad||amount<=0){alert('اطلاعات چک نامعتبر است.');return;}const companyId=getMySettings().default_company_id||getMyCompanies()[0]?.id||'';const p={direction:$('chq-direction-input').value,companyId,contactId:s?.value||'',contactName:s?.options[s.selectedIndex]?.text||'',sayad_id:sayad,bank:$('chq-bank-input').value||'',amount,due_date:$('chq-due-input').value||'',status:$('chq-status-input').value};if(getMyCheques().some(x=>x.id!==eq&&String(x.sayad_id||'')===sayad)){alert('شناسه صیادی تکراری است.');return;}if(eq){const q=datastore.cheques.find(x=>x.id===eq&&x.ownerUserId===currentUser.id);if(!q)return;if(q.status&&q.status!=='registered')return alert('چک تعیین‌تکلیف‌شده قابل بازنویسی نیست.');Object.assign(q,p);alert('چک اصلاح شد.');}else datastore.cheques.push({id:'CHQ_'+Date.now(),ownerUserId:currentUser.id,...p});saveDatastore();resetCheque();refreshAllSurfaces();};
window.deleteCheque=function(id){if(!requireWrite())return;const q=getMyCheques().find(x=>x.id===id);if(!q)return;if(q.status&&q.status!=='registered')return alert('چک تعیین‌تکلیف‌شده برای حفظ سابقه قابل حذف نیست.');if(!confirm('این چک ثبت‌شده حذف شود؟'))return;if(eq===id)resetCheque();datastore.cheques=datastore.cheques.filter(x=>!(x.id===id&&x.ownerUserId===currentUser.id));saveDatastore();refreshAllSurfaces();};
function chequeStatusLabel(status){return status==='cleared'?'وصول / پرداخت شده':status==='bounced'?'برگشتی / ناموفق':status==='cancelled'?'باطل شده':'در جریان';}
window.renderCheques=function(){const tb=$('cheques-ledger-table-body'),list=getMyCheques();if(!tb)return;tb.innerHTML=list.length?list.map(q=>`<tr><td>${q.direction==='inbound'?'دریافتی':'پرداختی'}</td><td>${esc(q.contactName||'—')}</td><td>${esc(q.bank)} - ${esc(q.sayad_id)}</td><td>${fmt(q.amount)}</td><td>${esc(q.due_date)}</td><td>${esc(chequeStatusLabel(q.status))}</td><td><button class="btn btn-secondary btn-inline" onclick="editCheque('${q.id}')">✏️ اصلاح</button> <button class="btn btn-danger btn-inline" onclick="deleteCheque('${q.id}')">حذف</button></td></tr>`).join(''):'<tr><td colspan="7" style="text-align:center;padding:20px">چکی ثبت نشده است.</td></tr>';};

// هزینه/درآمد
function refreshExpenseProjects(){
  const cs=$('trx-contact-select'),ps=$('trx-project-select');if(!cs||!ps)return;
  const prev=ps.value,c=getMyContacts().find(x=>x.id===cs.value),projects=Array.isArray(c?.projects)?c.projects:[];
  const opts=[];projects.forEach(p=>{opts.push({id:p.id,name:p.name});(p.subprojects||[]).forEach(s=>opts.push({id:s.id,name:(p.name+' / '+s.name)}));});
  ps.innerHTML='<option value="">بدون پروژه</option>'+opts.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('');
  if([...ps.options].some(o=>o.value===prev))ps.value=prev;
}
function refreshExpenseContacts(){
  const s=$('trx-contact-select');if(!s)return;const prev=s.value;
  s.innerHTML='<option value="">بدون طرف حساب</option>'+getMyContacts().map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('');
  if([...s.options].some(o=>o.value===prev))s.value=prev;refreshExpenseProjects();
}
window.refreshExpenseProjects=refreshExpenseProjects;
function resetExpense(){ee='';clr(['trx-amount-input','trx-desc-input']);if($('trx-contact-select'))$('trx-contact-select').value='';refreshExpenseProjects();btn('expense-save-btn','expense-edit-cancel-btn',false,'➕ ثبت سند','💾 ذخیره اصلاحات');}
window.cancelExpenseEdit=resetExpense;
window.editExpense=function(id){const e=getMyExpenses().find(x=>x.id===id);if(!e)return;ee=id;refreshExpenseContacts();$('trx-kind-input').value=e.kind;$('trx-category-input').value=e.category;$('trx-contact-select').value=e.contactId||'';refreshExpenseProjects();$('trx-project-select').value=e.projectId||'';$('trx-amount-input').value=fmt(e.amount);$('trx-desc-input').value=e.desc||'';btn('expense-save-btn','expense-edit-cancel-btn',true,'','💾 ذخیره اصلاحات');switchView('view-expenses');};
window.commitSaveExpense=function(){if(!requireWrite()||!currentUser)return;const amount=parseFormattedNumber($('trx-amount-input').value);if(amount<=0){alert('مبلغ معتبر نیست.');return;}const contactId=$('trx-contact-select')?.value||'',contact=getMyContacts().find(x=>x.id===contactId),projectId=$('trx-project-select')?.value||'',companyId=getMySettings().default_company_id||getMyCompanies()[0]?.id||'';const p={kind:$('trx-kind-input').value,category:$('trx-category-input').value,companyId,contactId,contactName:contact?.name||'',projectId,amount,desc:$('trx-desc-input').value||''};if(ee){const e=datastore.expenses.find(x=>x.id===ee&&x.ownerUserId===currentUser.id);if(!e)return;if(typeof jeGuardSourceMutation==='function'){try{jeGuardSourceMutation(e,'هزینه/درآمد');}catch(err){alert(err.message);return;}}Object.assign(e,p);alert('سند اصلاح شد.');}else{const rec={id:'TRX_'+Date.now(),ownerUserId:currentUser.id,...p,date:getJalaliNumeric()};datastore.expenses.push(rec);if(typeof jePostSourceRecord==='function'){try{jePostSourceRecord(rec.kind==='income'?'income':'expense',rec);}catch(err){datastore.expenses=datastore.expenses.filter(x=>x.id!==rec.id);alert('رکورد ثبت نشد: '+err.message);return;}}}saveDatastore();resetExpense();refreshAllSurfaces();};
window.deleteExpense=function(id){if(!requireWrite())return;const source=getMyExpenses().find(x=>x.id===id);if(typeof jeGuardSourceMutation==='function'){try{jeGuardSourceMutation(source,'هزینه/درآمد');}catch(e){alert(e.message);return;}}if(!confirm('این سند حذف شود؟'))return;if(ee===id)resetExpense();datastore.expenses=datastore.expenses.filter(x=>!(x.id===id&&x.ownerUserId===currentUser.id));saveDatastore();refreshAllSurfaces();};
window.renderExpenses=function(){const tb=$('expenses-ledger-table-body'),list=getMyExpenses();if(!tb)return;refreshExpenseContacts();const projectName=e=>{const c=getMyContacts().find(x=>x.id===e.contactId);for(const p of (c?.projects||[])){if(p.id===e.projectId)return p.name;const s=(p.subprojects||[]).find(x=>x.id===e.projectId);if(s)return p.name+' / '+s.name;}return e.projectId?'پروژه حذف/تغییر یافته':'—';};tb.innerHTML=list.length?list.map(e=>`<tr><td>${esc(e.kind)}</td><td>${esc(e.category)}</td><td>${esc(e.contactName||'—')}</td><td>${esc(projectName(e))}</td><td>${esc(e.desc)}</td><td>${fmt(e.amount)}</td><td><button class="btn btn-secondary btn-inline" onclick="editExpense('${e.id}')">✏️ اصلاح</button> <button class="btn btn-danger btn-inline" onclick="deleteExpense('${e.id}')">حذف</button></td></tr>`).join(''):'<tr><td colspan="7" style="text-align:center;padding:20px">موردی ثبت نشده است.</td></tr>';};

// فاکتور فروش: حذف در کنار ویرایش/چاپ
window.deleteInvoice=function(id){const source=getMyInvoices().find(x=>x.id===id);if(typeof jeGuardSourceMutation==='function'){try{jeGuardSourceMutation(source,'فاکتور فروش');}catch(e){alert(e.message);return;}}if(typeof getMyPayments==='function'&&getMyPayments().some(p=>p.invoiceType==='sale'&&p.invoiceId===id)){alert('برای این فاکتور دریافت ثبت شده است؛ برای حفظ سابقه مالی ابتدا تخصیص دریافت را اصلاح کنید.');return;}if(!requireWrite()||!confirm('این فاکتور حذف شود؟'))return;datastore.invoices=datastore.invoices.filter(x=>!(x.id===id&&x.ownerUserId===currentUser.id));saveDatastore();refreshAllSurfaces();};
const ri=window.renderInvoices;window.renderInvoices=function(){ri();document.querySelectorAll('#invoice-archive-table-body tr').forEach(tr=>{const edit=tr.querySelector('button[onclick^="editInvoice"]');if(!edit)return;const m=(edit.getAttribute('onclick')||'').match(/editInvoice\('([^']+)'\)/);if(!m)return;const cell=tr.lastElementChild;if(cell&&!cell.querySelector('.delete-invoice')){const b=document.createElement('button');b.className='btn btn-danger btn-inline delete-invoice';b.style.cssText='padding:4px 8px;font-size:12px;min-height:30px';b.textContent='حذف';b.onclick=()=>deleteInvoice(m[1]);cell.appendChild(b);}});};
try{if(currentUser)refreshAllSurfaces();}catch(e){console.error('crud init',e);}
})();