/* Finora modular platform foundation: commercial entitlements, module launcher and admin picker. */
(function(){
const MODULE_CATALOG={
 core:{title:'هسته فینورا',icon:'⌂',implemented:true},accounting:{title:'حسابداری',icon:'▦',implemented:true},commerce:{title:'بازرگانی',icon:'⇄',implemented:true},treasury:{title:'خزانه‌داری',icon:'◈',implemented:true},contracting:{title:'پیمان‌ها',icon:'▧',implemented:true},inventory:{title:'انبار',icon:'▦',implemented:true},assets:{title:'دارایی ثابت',icon:'◆',implemented:true},hr_payroll:{title:'منابع انسانی و حقوق',icon:'♙',implemented:true},office_automation:{title:'اتوماسیون اداری',icon:'✉',implemented:true},requests_workflow:{title:'درخواست‌ها و فرایندها',icon:'✓',implemented:true},group_consolidation:{title:'گروه و بین‌شرکتی',icon:'◎',implemented:true},analytics:{title:'گزارش و تحلیل',icon:'▥',implemented:true},crm:{title:'CRM و فروش',icon:'◇',implemented:false},transport:{title:'حمل‌ونقل و ناوگان',icon:'⌁',implemented:false},manufacturing:{title:'تولید و MRP',icon:'⚙',implemented:false},maintenance:{title:'نگهداری و تعمیرات',icon:'⌘',implemented:false}
};
window.FINORA_MODULE_CATALOG=MODULE_CATALOG;
const newColls=['officeRegistries','correspondence','correspondenceAttachments','correspondenceReferrals','correspondenceAudit','requestTypes','requests','requestActions'];
if(typeof COLLS!=='undefined')newColls.forEach(k=>{if(!COLLS.includes(k))COLLS.push(k)});
if(typeof datastore!=='undefined')newColls.forEach(k=>{if(!Array.isArray(datastore[k]))datastore[k]=[]});
if(typeof buildUserFromRows==='function'){const baseBuild=buildUserFromRows;buildUserFromRows=function(profile,lic){const u=baseBuild(profile,lic);u.modules=Array.isArray(lic?.modules)&&lic.modules.length?lic.modules.slice():['full_suite'];return u}}
function licensed(key){if(key==='core')return true;if(!currentUser)return false;const mods=Array.isArray(currentUser.modules)&&currentUser.modules.length?currentUser.modules:['full_suite'];return mods.includes('full_suite')||mods.includes(key)}
window.hasLicensedModule=licensed;
function shellEntitlement(moduleKey,task=''){
 if(['dashboard','settings'].includes(moduleKey))return 'core';if(moduleKey==='accounting')return 'accounting';if(moduleKey==='commerce')return 'commerce';if(moduleKey==='treasury')return 'treasury';if(moduleKey==='projects')return 'contracting';if(moduleKey==='inventory')return 'inventory';if(moduleKey==='assets')return 'assets';if(moduleKey==='office')return 'office_automation';if(moduleKey==='requests')return 'requests_workflow';if(moduleKey==='reports')return licensed('analytics')?'analytics':'accounting';
 if(moduleKey==='enterprise'){if(['employees','contracts','leave','payroll','benefits'].includes(task))return 'hr_payroll';if(['treasury','pettyops'].includes(task))return 'treasury';if(task==='group')return 'group_consolidation';return 'accounting'}return 'core'
}
function canModule(moduleKey,task=''){if(moduleKey==='enterprise'&&!task)return ['hr_payroll','treasury','group_consolidation','accounting'].some(licensed);if(moduleKey==='reports'&&!task)return licensed('analytics')||licensed('accounting');return licensed(shellEntitlement(moduleKey,task))}
window.canAccessFinoraModule=canModule;
function registerShellModules(){
 if(typeof FINORA_MODULES==='undefined')return;
 if(!FINORA_MODULES.office)FINORA_MODULES.office={title:'اتوماسیون اداری',context:'دبیرخانه، مکاتبات، اسکن و بایگانی',groups:[{title:'دبیرخانه',items:[['کارتابل مکاتبات','view-office','✉','','inbox'],['ثبت نامه','view-office','＋','','new'],['دفاتر و شماره‌گذاری','view-office','▤','','registries'],['قالب‌های نامه','view-office','▧','','templates']]},{title:'گردش و پیگیری',items:[['ارجاعات و پیگیری','view-office','↪','','work']]},{title:'بایگانی و کنترل',items:[['جست‌وجو و آرشیو','view-office','⌕','','archive'],['پیوست‌ها و اسکن','view-office','▣','','attachments']]}]};
 if(!FINORA_MODULES.requests)FINORA_MODULES.requests={title:'درخواست‌ها',context:'فرم‌ساز و گردش درخواست‌های سازمانی',groups:[{title:'کار من',items:[['درخواست جدید','view-requests','＋','','new'],['درخواست‌های من','view-requests','▤','','mine']]},{title:'راه‌اندازی',items:[['انواع درخواست و فرم‌ساز','view-requests','⚙','','types']]}]};
 if(typeof FINORA_VIEW_HOME!=='undefined'){FINORA_VIEW_HOME['view-office']='office';FINORA_VIEW_HOME['view-requests']='requests'}
 if(typeof FINORA_COMMANDS!=='undefined')[['office',FINORA_MODULES.office],['requests',FINORA_MODULES.requests]].forEach(([module,m])=>m.groups.forEach(g=>g.items.forEach(i=>{if(!FINORA_COMMANDS.some(x=>x.module===module&&x.view===i[1]&&x.task===(i[4]||'')))FINORA_COMMANDS.push({module,moduleTitle:m.title,groupTitle:g.title,title:i[0],view:i[1],icon:i[2],guard:i[3]||'',task:i[4]||''})})));
}
function injectRail(){const rail=document.getElementById('module-rail');if(!rail)return;const before=rail.querySelector('[data-module="reports"]');[['office','view-office','✉','اتوماسیون','inbox'],['requests','view-requests','✓','درخواست‌ها','new']].forEach(([m,v,ic,label,task])=>{if(rail.querySelector('[data-module="'+m+'"]'))return;const b=document.createElement('button');b.className='module-tab';b.dataset.module=m;b.dataset.view=v;b.title=label;b.innerHTML='<span>'+ic+'</span><b>'+label+'</b>';b.onclick=()=>openModule(m,v,task);rail.insertBefore(b,before||null)})}
function applyLicensedUI(){injectRail();document.querySelectorAll('.module-tab').forEach(b=>{b.style.display=canModule(b.dataset.module||'core','')?'':'none'})}
window.applyLicensedModuleUI=applyLicensedUI;
registerShellModules();
if(typeof canShowShellCommand==='function'){const baseCan=canShowShellCommand;canShowShellCommand=function(cmd){if(!baseCan(cmd))return false;if(cmd&&cmd.module)return canModule(cmd.module,cmd.task||'');return true}}
if(typeof renderModulePanel==='function'){const basePanel=renderModulePanel;renderModulePanel=function(moduleKey,activeView,activeTask=''){if(!canModule(moduleKey,activeTask||'')){showModuleLauncher(true);return}basePanel(moduleKey,activeView,activeTask);const box=document.getElementById('module-panel-links');if(box)box.querySelectorAll('.module-link').forEach(btn=>{const task=btn.dataset.task||'',view=btn.dataset.view||'',cmd=typeof FINORA_COMMANDS!=='undefined'?FINORA_COMMANDS.find(x=>x.module===moduleKey&&x.view===view&&x.task===task):null;if(cmd&&!canModule(moduleKey,task))btn.remove()})}}
if(typeof openModule==='function'){const baseOpen=openModule;openModule=function(moduleKey,defaultView,defaultTask=''){if(!canModule(moduleKey,defaultTask||'')){alert('این ماژول در لایسنس فعلی فعال نیست.');return showModuleLauncher(true)}return baseOpen(moduleKey,defaultView,defaultTask)}}
if(typeof navigateShell==='function'){const baseNav=navigateShell;navigateShell=function(moduleKey,viewId,task='',rerender=true){if(!canModule(moduleKey,task||'')){alert('دسترسی این ماژول در لایسنس فعلی فعال نیست.');return false}return baseNav(moduleKey,viewId,task,rerender)}}
if(typeof refreshAllSurfaces==='function'){const baseRefresh=refreshAllSurfaces;refreshAllSurfaces=function(){const r=baseRefresh();applyLicensedUI();if(document.getElementById('view-office')?.classList.contains('active')&&typeof officeRender==='function')officeRender(window.FINORA_OFFICE_TASK||'inbox');if(document.getElementById('view-requests')?.classList.contains('active')&&typeof requestsRender==='function')requestsRender(window.FINORA_REQUEST_TASK||'mine');return r}}
function launcherModules(){const list=[['accounting','accounting','view-accounting-foundation','accounts'],['commerce','commerce','view-invoices',''],['treasury','treasury','view-payments',''],['contracting','projects','view-contracting',''],['inventory','inventory','view-inventory','stock'],['assets','assets','view-assets','asset-register'],['hr_payroll','enterprise','view-enterprise','employees'],['office_automation','office','view-office','inbox'],['requests_workflow','requests','view-requests','new'],['group_consolidation','enterprise','view-enterprise','group'],['analytics','reports','view-reports','']];return list.filter(x=>licensed(x[0]))}
function ensureLauncher(){let el=document.getElementById('finora-module-launcher');if(el)return el;el=document.createElement('div');el.id='finora-module-launcher';el.className='modal-backdrop';el.innerHTML='<div class="modal-card" style="max-width:860px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><h3 style="font-size:20px">ورود به فضای کاری</h3><p style="color:var(--text-muted);font-size:12px;margin-top:5px">فقط ماژول‌های فعال در لایسنس شما نمایش داده می‌شوند.</p></div><button class="btn btn-secondary btn-inline" onclick="closeModuleLauncher()">ادامه در داشبورد</button></div><div id="finora-launcher-grid" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:18px"></div></div>';document.body.appendChild(el);return el}
function showModuleLauncher(force=false){if(!currentUser)return;const choices=launcherModules();if(!force&&choices.length<=1)return;const el=ensureLauncher(),grid=document.getElementById('finora-launcher-grid');grid.innerHTML=choices.map(x=>{const c=MODULE_CATALOG[x[0]];return '<button class="card" style="text-align:right;cursor:pointer;border:1px solid var(--border);padding:16px" onclick="enterLicensedWorkspace(\''+x[1]+'\',\''+x[2]+'\',\''+x[3]+'\')"><div style="font-size:24px">'+c.icon+'</div><strong style="display:block;margin-top:8px">'+c.title+'</strong><small style="color:var(--text-muted)">ورود به ماژول</small></button>'}).join('');el.classList.add('active')}
window.showModuleLauncher=showModuleLauncher;window.closeModuleLauncher=()=>document.getElementById('finora-module-launcher')?.classList.remove('active');window.enterLicensedWorkspace=(m,v,t)=>{closeModuleLauncher();navigateShell(m,v,t||'')};
function ensureLicensePicker(){const modal=document.querySelector('#modal-admin-license-edit .modal-card');if(!modal||document.getElementById('modal-license-modules'))return;const actions=modal.querySelector('div[style*="margin-top:16px"]'),box=document.createElement('div');box.id='modal-license-modules';box.className='form-group';box.innerHTML='<label>ماژول‌های فعال لایسنس</label><div id="license-module-grid" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:8px"></div><small style="color:var(--text-muted)">«کامل» همه ماژول‌های فعلی و آینده را باز می‌کند. ماژول‌های آتی تا زمان عملیاتی‌شدن قابل فروش نیستند.</small>';modal.insertBefore(box,actions||null)}
function renderLicensePicker(uid){ensureLicensePicker();const u=typeof adminUsersCache!=='undefined'?adminUsersCache.find(x=>x.id===uid):null,mods=Array.isArray(u?.lic?.modules)&&u.lic.modules.length?u.lic.modules:['full_suite'],grid=document.getElementById('license-module-grid');if(!grid)return;grid.innerHTML='<label style="grid-column:1/-1"><input type="checkbox" value="full_suite" '+(mods.includes('full_suite')?'checked':'')+' onchange="toggleFullSuiteModules(this)"> <strong>لایسنس کامل ERP</strong></label>'+Object.entries(MODULE_CATALOG).filter(([k])=>k!=='core').map(([k,v])=>'<label style="opacity:'+(v.implemented?1:.5)+'"><input class="license-module-check" type="checkbox" value="'+k+'" '+(mods.includes('full_suite')||mods.includes(k)?'checked':'')+' '+(v.implemented?'':'disabled')+'> '+v.title+(v.implemented?'':' — آتی')+'</label>').join('');toggleFullSuiteModules(grid.querySelector('input[value="full_suite"]'),true)}
window.toggleFullSuiteModules=function(el,keep){document.querySelectorAll('.license-module-check').forEach(x=>{if(el?.checked){x.checked=true;x.disabled=true}else{x.disabled=!MODULE_CATALOG[x.value]?.implemented;if(!keep&&MODULE_CATALOG[x.value]?.implemented)x.checked=false}})};
if(typeof openLicenseEditModal==='function'){const baseOpenLicense=openLicenseEditModal;openLicenseEditModal=function(uid){baseOpenLicense(uid);renderLicensePicker(uid)}}
if(typeof applyLicenseDurationChange==='function')applyLicenseDurationChange=async function(){
 const uid=document.getElementById('modal-license-target-username').value,plan=document.getElementById('modal-license-duration-select').value,u=adminUsersCache.find(x=>x.id===uid);
 const companyReady=!!(u?.lic&&Object.prototype.hasOwnProperty.call(u.lic,'max_companies')),userReady=!!(u?.lic&&Object.prototype.hasOwnProperty.call(u.lic,'max_users'));
 const cap=Math.max(1,Math.min(1000,Number(document.getElementById('modal-license-company-limit')?.value||1)));
 const userCap=Math.max(1,Math.min(100000,Number(document.getElementById('modal-license-user-limit')?.value||1)));
 const full=document.querySelector('#license-module-grid input[value="full_suite"]')?.checked,mods=full?['full_suite']:[...document.querySelectorAll('.license-module-check:checked:not(:disabled)')].map(x=>x.value);
 if(!mods.length)return alert('حداقل یک ماژول عملیاتی را انتخاب کنید.');
 closeLicenseEditModal();
 let ok=await adminRpc('admin_set_license',{target:uid,new_plan:plan,new_status:'active'},'');if(!ok)return false;
 if(companyReady){ok=await adminRpc('admin_set_company_limit',{target:uid,new_max_companies:cap},'');if(!ok)return false}
 if(userReady){ok=await adminRpc('admin_set_user_limit',{target:uid,new_max_users:userCap},'');if(!ok)return false}
 ok=await adminRpc('admin_set_license_modules',{target:uid,new_modules:mods},'لایسنس، ظرفیت شرکت، ظرفیت کاربران و ماژول‌ها اعمال شد.');
 if(ok&&currentUser?.id===uid){currentUser=await fetchCurrentUser({id:uid});await pullAll();refreshAllSurfaces()}
 return ok
};
if(typeof enterApp==='function'){const baseEnter=enterApp;enterApp=async function(authUser){await baseEnter(authUser);if(!currentUser)return;applyLicensedUI()}}
applyLicensedUI();
})();