// پروژه و زیرپروژه برای طرف حساب‌های پروژه‌محور
function getContactProjects(contactId){const c=getMyContacts().find(x=>x.id===contactId);if(!c)return[];if(!Array.isArray(c.projects))c.projects=[];c.projects.forEach(p=>{if(!p.direction)p.direction='both';if(!Array.isArray(p.subprojects))p.subprojects=[];});return c.projects;}
function projectDirectionLabel(d){return d==='sale'?'فروش':d==='purchase'?'خرید':'خرید و فروش';}
function askProjectDirection(current='both'){const v=(prompt('نوع پروژه: sale = فروش، purchase = خرید، both = هر دو',current)||current).trim().toLowerCase();return ['sale','purchase','both'].includes(v)?v:'both';}
function addProjectToContact(contactId){if(!requireWrite())return;const c=getMyContacts().find(x=>x.id===contactId);if(!c)return;const name=prompt('نام پروژه جدید را وارد کنید:');if(!name||!name.trim())return;getContactProjects(contactId).push({id:'PRJ_'+Date.now(),name:name.trim(),direction:askProjectDirection(),subprojects:[]});c.project_mode='multi';saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);}
function editContactProject(contactId,projectId){if(!requireWrite())return;const p=getContactProjects(contactId).find(x=>x.id===projectId);if(!p)return;const n=prompt('نام پروژه:',p.name);if(!n||!n.trim())return;p.name=n.trim();p.direction=askProjectDirection(p.direction);saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);}
function deleteContactProject(contactId,projectId){
  if(!requireWrite())return;
  const p=getContactProjects(contactId).find(x=>x.id===projectId);if(!p)return;
  const ids=[projectId,...(p.subprojects||[]).map(s=>s.id)];
  const usedSale=getMyInvoices().some(i=>ids.includes(i.projectId));
  const usedBuy=(datastore.purchases||[]).some(x=>x.ownerUserId===currentUser?.id&&ids.includes(x.costCenterId));
  const usedExpense=getMyExpenses().some(x=>ids.includes(x.projectId));
  const usedPayment=typeof getMyPayments==='function'&&getMyPayments().some(x=>ids.includes(x.projectId));
  if(usedSale||usedBuy||usedExpense||usedPayment){alert('این پروژه یا یکی از زیرپروژه‌های آن در سند مالی استفاده شده و برای حفظ سابقه قابل حذف نیست.');return;}
  if(!confirm('پروژه و همه زیرپروژه‌های آن حذف شود؟'))return;
  const c=getMyContacts().find(x=>x.id===contactId);if(!c)return;c.projects=getContactProjects(contactId).filter(x=>x.id!==projectId);saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);
}
function addSubproject(contactId,projectId){if(!requireWrite())return;const p=getContactProjects(contactId).find(x=>x.id===projectId);if(!p)return;const n=prompt('نام زیرپروژه:');if(!n||!n.trim())return;p.subprojects.push({id:'SUB_'+Date.now(),name:n.trim()});saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);}
function editSubproject(contactId,projectId,subId){if(!requireWrite())return;const p=getContactProjects(contactId).find(x=>x.id===projectId),s=p?.subprojects?.find(x=>x.id===subId);if(!s)return;const n=prompt('نام زیرپروژه:',s.name);if(!n||!n.trim())return;s.name=n.trim();saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);}
function deleteSubproject(contactId,projectId,subId){
  if(!requireWrite())return;
  const usedSale=getMyInvoices().some(i=>i.projectId===subId);
  const usedBuy=(datastore.purchases||[]).some(x=>x.ownerUserId===currentUser?.id&&x.costCenterId===subId);
  const usedExpense=getMyExpenses().some(x=>x.projectId===subId);
  const usedPayment=typeof getMyPayments==='function'&&getMyPayments().some(x=>x.projectId===subId);
  if(usedSale||usedBuy||usedExpense||usedPayment){alert('این زیرپروژه در سند مالی استفاده شده و برای حفظ سابقه قابل حذف نیست.');return;}
  if(!confirm('زیرپروژه حذف شود؟'))return;const p=getContactProjects(contactId).find(x=>x.id===projectId);if(!p)return;p.subprojects=p.subprojects.filter(x=>x.id!==subId);saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);
}
function ensureProjectModal(){if(document.getElementById('project-manager-modal'))return;const d=document.createElement('div');d.id='project-manager-modal';d.className='modal-backdrop';d.innerHTML='<div class="modal-card" style="max-width:900px;max-height:85vh;overflow:auto"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 id="project-manager-title"></h3><button class="btn btn-secondary btn-inline" onclick="document.getElementById(\'project-manager-modal\').classList.remove(\'active\')">✕ بستن</button></div><div id="project-manager-body"></div></div>';document.body.appendChild(d);}
function manageContactProjects(contactId){const c=getMyContacts().find(x=>x.id===contactId);if(!c)return;ensureProjectModal();document.getElementById('project-manager-title').innerText='پروژه‌ها و زیرپروژه‌های '+c.name;const ps=getContactProjects(contactId);const rows=ps.length?ps.map(p=>`<tr><td><b>${esc(p.name)}</b><div style="font-size:11px;color:var(--text-muted)">${projectDirectionLabel(p.direction)}</div></td><td>${p.subprojects.length?p.subprojects.map(s=>`<div style="padding:5px 0;border-bottom:1px solid #eee;display:flex;justify-content:space-between;gap:8px"><span>${esc(s.name)}</span><span><button class="btn btn-secondary btn-inline" onclick="editSubproject('${contactId}','${p.id}','${s.id}')">اصلاح</button> <button class="btn btn-danger btn-inline" onclick="deleteSubproject('${contactId}','${p.id}','${s.id}')">حذف</button></span></div>`).join(''):'—'}</td><td><button class="btn btn-secondary btn-inline" onclick="addSubproject('${contactId}','${p.id}')">➕ زیرپروژه</button> <button class="btn btn-secondary btn-inline" onclick="editContactProject('${contactId}','${p.id}')">✏️ اصلاح</button> <button class="btn btn-danger btn-inline" onclick="deleteContactProject('${contactId}','${p.id}')">حذف</button></td></tr>`).join(''):'<tr><td colspan="3" style="text-align:center;padding:18px">پروژه‌ای تعریف نشده است.</td></tr>';document.getElementById('project-manager-body').innerHTML=`<button class="btn btn-primary btn-inline" style="margin-bottom:12px" onclick="addProjectToContact('${contactId}')">➕ پروژه جدید</button><div class="table-responsive"><table><thead><tr><th>پروژه</th><th>زیرپروژه‌ها</th><th>عملیات</th></tr></thead><tbody>${rows}</tbody></table></div>`;document.getElementById('project-manager-modal').classList.add('active');}
function handleInvoiceContactChange(){const contactId=document.getElementById('invoice-contact-id')?.value,c=getMyContacts().find(x=>x.id===contactId),row=document.getElementById('box-invoice-project-row'),sel=document.getElementById('invoice-project-id');if(!row||!sel)return;const opts=[];if(c&&c.project_mode==='multi')getContactProjects(contactId).filter(p=>p.direction!=='purchase').forEach(p=>{opts.push(`<option value="${p.id}">${esc(p.name)}</option>`);p.subprojects.forEach(s=>opts.push(`<option value="${s.id}">↳ ${esc(p.name)} / ${esc(s.name)}</option>`));});row.style.display=opts.length?'flex':'none';sel.innerHTML=opts.join('');}
(function(){const base=window.renderContacts;if(typeof base!=='function')return;window.renderContacts=function(){base();const cs=getMyContacts(),rows=document.querySelectorAll('#contacts-ledger-table-body tr');rows.forEach((tr,i)=>{const c=cs[i];if(!c||!tr.cells||tr.cells.length<8)return;const cell=tr.cells[7];if(c.project_mode==='multi')cell.innerHTML=`<button class="btn btn-secondary btn-inline" style="padding:2px 7px;font-size:11px" onclick="manageContactProjects('${c.id}')">📁 مدیریت ${getContactProjects(c.id).length.toLocaleString('fa-IR')} پروژه</button>`;});};})();