// پروژه‌ها یک Master Data سراسری شرکت هستند؛ طرف حساب فقط به پروژه‌های موجود متصل می‌شود.
function projectDirectionLabel(d){return d==='sale'?'فروش':d==='purchase'?'خرید':'خرید و فروش';}
function projectLinkableForContact(p,contactId){return p&&p.active!==false&&(!(p.linkedContactIds||[]).length||(p.linkedContactIds||[]).includes(contactId));}
function getContactProjects(contactId){
  if(typeof afMigrateLegacyProjects==='function')try{afMigrateLegacyProjects();}catch(_){}
  const all=(typeof getMyGlobalProjects==='function'?getMyGlobalProjects():[]),linked=all.filter(p=>(p.linkedContactIds||[]).includes(contactId)),top=linked.filter(p=>!p.parentId||!linked.some(x=>x.id===p.parentId));
  return top.map(p=>({...p,subprojects:linked.filter(s=>s.parentId===p.id)}));
}
function ensureProjectDirectionModal(){
  if(document.getElementById('project-direction-modal'))return;
  const d=document.createElement('div');d.id='project-direction-modal';d.className='modal-backdrop';d.innerHTML='<div class="modal-card" style="max-width:420px"><h3 style="margin-bottom:12px">نوع گردش پروژه</h3><div class="form-group"><label>کاربرد پروژه</label><select id="project-direction-select" class="form-control"><option value="both">خرید و فروش</option><option value="sale">فروش</option><option value="purchase">خرید</option></select></div><div style="display:flex;gap:8px;justify-content:flex-end"><button class="btn btn-secondary btn-inline" id="project-direction-cancel">انصراف</button><button class="btn btn-primary btn-inline" id="project-direction-ok">تأیید</button></div></div>';document.body.appendChild(d);
}
function askProjectDirection(current='both'){
  ensureProjectDirectionModal();const modal=document.getElementById('project-direction-modal'),sel=document.getElementById('project-direction-select');sel.value=['sale','purchase','both'].includes(current)?current:'both';modal.classList.add('active');
  return new Promise(resolve=>{const finish=v=>{modal.classList.remove('active');document.getElementById('project-direction-ok').onclick=null;document.getElementById('project-direction-cancel').onclick=null;resolve(v)};document.getElementById('project-direction-ok').onclick=()=>finish(sel.value);document.getElementById('project-direction-cancel').onclick=()=>finish(current)});
}
function ensureProjectAttachModal(){
 if(document.getElementById('project-attach-modal'))return;const d=document.createElement('div');d.id='project-attach-modal';d.className='modal-backdrop';
 d.innerHTML='<div class="modal-card" style="max-width:620px"><div style="display:flex;justify-content:space-between;align-items:center"><h3>اتصال پروژه به طرف حساب</h3><button class="btn btn-secondary btn-inline" onclick="closeProjectAttachModal()">✕ بستن</button></div><p class="af-hint">ابتدا پروژه‌های موجود شرکت را جستجو و انتخاب کنید؛ فقط اگر پروژه وجود ندارد، همان‌جا پروژه جدید بسازید.</p><div class="form-group"><label>جستجو در پروژه‌های موجود</label><input id="project-attach-search" class="form-control" placeholder="نام یا کد پروژه..." oninput="renderProjectAttachOptions()"><select id="project-attach-existing" class="form-control" size="6" style="margin-top:6px"></select></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-primary" onclick="attachExistingProject()">اتصال پروژه انتخاب‌شده</button></div><hr style="margin:16px 0"><h4>پروژه در فهرست نیست؟</h4><div class="form-row"><div class="form-group"><label>کد پروژه</label><input id="project-new-code" class="form-control"></div><div class="form-group"><label>نام پروژه</label><input id="project-new-name" class="form-control"></div></div><button class="btn btn-success" onclick="createAndAttachProject()">ایجاد و اتصال پروژه جدید</button></div>';document.body.appendChild(d);
}
let FINORA_PROJECT_CONTACT='';
function closeProjectAttachModal(){document.getElementById('project-attach-modal')?.classList.remove('active')}
function renderProjectAttachOptions(){
 const sel=document.getElementById('project-attach-existing');if(!sel)return;const q=(document.getElementById('project-attach-search')?.value||'').trim().toLowerCase(),all=typeof getMyGlobalProjects==='function'?getMyGlobalProjects():[],linked=new Set(getContactProjects(FINORA_PROJECT_CONTACT).flatMap(p=>[p.id,...(p.subprojects||[]).map(s=>s.id)])),rows=all.filter(p=>p.active!==false&&!p.parentId&&!linked.has(p.id)).filter(p=>!q||(String(p.code||'')+' '+String(p.name||'')).toLowerCase().includes(q));
 sel.innerHTML=rows.map(p=>'<option value="'+esc(p.id)+'">'+esc((p.code?p.code+' — ':'')+p.name)+'</option>').join('')||'<option value="">پروژه آزاد دیگری یافت نشد</option>';
}
function openProjectAttachModal(contactId){FINORA_PROJECT_CONTACT=contactId;ensureProjectAttachModal();document.getElementById('project-attach-search').value='';document.getElementById('project-new-code').value='';document.getElementById('project-new-name').value='';renderProjectAttachOptions();document.getElementById('project-attach-modal').classList.add('active')}
function attachExistingProject(){
 if(!requireWrite())return;const id=document.getElementById('project-attach-existing')?.value,p=(typeof getMyGlobalProjects==='function'?getMyGlobalProjects():[]).find(x=>x.id===id);if(!p)return alert('یک پروژه موجود را انتخاب کنید.');p.linkedContactIds=[...new Set([...(p.linkedContactIds||[]),FINORA_PROJECT_CONTACT])];const c=getMyContacts().find(x=>x.id===FINORA_PROJECT_CONTACT);if(c)c.project_mode='multi';saveDatastore();closeProjectAttachModal();refreshAllSurfaces();manageContactProjects(FINORA_PROJECT_CONTACT);
}
async function createAndAttachProject(){
 if(!requireWrite())return;const name=document.getElementById('project-new-name')?.value.trim(),code=(document.getElementById('project-new-code')?.value.trim()||('PRJ-'+(getMyGlobalProjects().length+1)));if(!name)return alert('نام پروژه الزامی است.');if(getMyGlobalProjects().some(p=>p.code===code))return alert('کد پروژه تکراری است.');const direction=await askProjectDirection('both'),p={id:'PRJ_'+Date.now(),ownerUserId:currentUser.id,companyId:afCompanyId(),code,name,floatingCode:typeof afNextFloatingCode==='function'?afNextFloatingCode(3,1):'',parentId:'',branchId:'',linkedContactIds:[FINORA_PROJECT_CONTACT],direction,active:true};datastore.projects.push(p);const c=getMyContacts().find(x=>x.id===FINORA_PROJECT_CONTACT);if(c)c.project_mode='multi';saveDatastore();closeProjectAttachModal();refreshAllSurfaces();manageContactProjects(FINORA_PROJECT_CONTACT);
}
function addProjectToContact(contactId){openProjectAttachModal(contactId)}
function detachContactProject(contactId,projectId){
 if(!requireWrite())return;const all=getMyGlobalProjects(),p=all.find(x=>x.id===projectId);if(!p)return;if(!confirm('اتصال این پروژه از طرف حساب برداشته شود؟ خود پروژه و سوابق آن حذف نمی‌شود.'))return;p.linkedContactIds=(p.linkedContactIds||[]).filter(id=>id!==contactId);all.filter(x=>x.parentId===projectId).forEach(x=>x.linkedContactIds=(x.linkedContactIds||[]).filter(id=>id!==contactId));saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);
}
async function addSubproject(contactId,projectId){
 if(!requireWrite())return;const parent=getMyGlobalProjects().find(x=>x.id===projectId);if(!parent)return;const n=prompt('نام زیرپروژه:');if(!n||!n.trim())return;const direction=await askProjectDirection(parent.direction||'both');datastore.projects.push({id:'SUB_'+Date.now(),ownerUserId:currentUser.id,companyId:afCompanyId(),code:(parent.code||projectId)+'-'+(getMyGlobalProjects().filter(x=>x.parentId===projectId).length+1),name:n.trim(),floatingCode:typeof afNextFloatingCode==='function'?afNextFloatingCode(3,1):'',parentId:projectId,branchId:parent.branchId||'',linkedContactIds:[contactId],direction,active:true});saveDatastore();refreshAllSurfaces();manageContactProjects(contactId);
}
function ensureProjectModal(){if(document.getElementById('project-manager-modal'))return;const d=document.createElement('div');d.id='project-manager-modal';d.className='modal-backdrop';d.innerHTML='<div class="modal-card" style="max-width:900px;max-height:85vh;overflow:auto"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 id="project-manager-title"></h3><button class="btn btn-secondary btn-inline" onclick="document.getElementById(\'project-manager-modal\').classList.remove(\'active\')">✕ بستن</button></div><div id="project-manager-body"></div></div>';document.body.appendChild(d)}
function manageContactProjects(contactId){
 const c=getMyContacts().find(x=>x.id===contactId);if(!c)return;ensureProjectModal();document.getElementById('project-manager-title').innerText='پروژه‌های متصل به '+c.name;const ps=getContactProjects(contactId),rows=ps.length?ps.map(p=>'<tr><td><b>'+esc((p.code?p.code+' — ':'')+p.name)+'</b><div style="font-size:11px;color:var(--text-muted)">'+projectDirectionLabel(p.direction)+'</div></td><td>'+((p.subprojects||[]).length?(p.subprojects||[]).map(s=>'<div style="padding:5px 0;border-bottom:1px solid #eee">'+esc(s.name)+'</div>').join(''):'—')+'</td><td><button class="btn btn-secondary btn-inline" onclick="addSubproject(\''+contactId+'\',\''+p.id+'\')">➕ زیرپروژه</button> <button class="btn btn-danger btn-inline" onclick="detachContactProject(\''+contactId+'\',\''+p.id+'\')">قطع اتصال</button></td></tr>').join(''):'<tr><td colspan="3" style="text-align:center;padding:18px">پروژه‌ای به این طرف حساب متصل نشده است.</td></tr>';
 document.getElementById('project-manager-body').innerHTML='<button class="btn btn-primary btn-inline" style="margin-bottom:12px" onclick="openProjectAttachModal(\''+contactId+'\')">＋ انتخاب پروژه موجود / ایجاد پروژه جدید</button><div class="table-responsive"><table><thead><tr><th>پروژه</th><th>زیرپروژه‌ها</th><th>عملیات</th></tr></thead><tbody>'+rows+'</tbody></table></div>';document.getElementById('project-manager-modal').classList.add('active');
}
function handleInvoiceContactChange(){const contactId=document.getElementById('invoice-contact-id')?.value,row=document.getElementById('box-invoice-project-row'),sel=document.getElementById('invoice-project-id');if(!row||!sel)return;const opts=[];getContactProjects(contactId).filter(p=>(p.direction||'both')!=='purchase').forEach(p=>{opts.push('<option value="'+esc(p.id)+'">'+esc((p.code?p.code+' — ':'')+p.name)+'</option>');(p.subprojects||[]).filter(s=>(s.direction||p.direction||'both')!=='purchase').forEach(s=>opts.push('<option value="'+esc(s.id)+'">↳ '+esc(p.name)+' / '+esc(s.name)+'</option>'))});row.style.display=opts.length?'flex':'none';sel.innerHTML=opts.join('');if(typeof finoraRefreshSearchableSelect==='function')finoraRefreshSearchableSelect(sel)}
(function(){const base=window.renderContacts;if(typeof base!=='function')return;window.renderContacts=function(){base();const cs=getMyContacts(),rows=document.querySelectorAll('#contacts-ledger-table-body tr');rows.forEach((tr,i)=>{const c=cs[i];if(!c||!tr.cells||tr.cells.length<8)return;const cell=tr.cells[7];if(c.project_mode==='multi'||getContactProjects(c.id).length)cell.innerHTML='<button class="btn btn-secondary btn-inline" style="padding:2px 7px;font-size:11px" onclick="manageContactProjects(\''+c.id+'\')">📁 مدیریت '+getContactProjects(c.id).length.toLocaleString('fa-IR')+' پروژه</button>';else cell.innerHTML='<button class="btn btn-secondary btn-inline" style="padding:2px 7px;font-size:11px" onclick="openProjectAttachModal(\''+c.id+'\')">＋ اتصال پروژه</button>'})}})();
