-- NO-OP: superseded by production-applied migration 20260929221754_iran_enterprise_financial_controls.sql.
-- Kept only to document the originally prepared future filename and prevent duplicate DDL.
