alter table public.records drop constraint if exists records_collection_check;
alter table public.records add constraint records_collection_check check (collection = any (array['companies','contacts','products','invoices','cheques','expenses','settings','purchases','payments','fiscalYears','accounts','dimensionTypes','dimensionValues','accountDimensionRules','branches','projects','projectLinks','postingProfiles','journalVouchers','journalLines','journalLineDimensions','contracts','contractAmendments','contractParties','contractDeductions','guarantees','guaranteeEvents','contractStatements','phase4Audit','warehouses','stockMovements','inventoryCounts','fixedAssets','assetDepreciations','currencies','exchangeRates','costCenters','importBatches','integrationConnections','integrationOutbox','phase5Audit','employees','employmentContracts','employeeLeave','cashboxes','pettyCashFunds','complianceRules','payrollRuns','payrollLines','employeeBenefitAccruals','pettyCashTransactions','budgets','costDrivers','costAllocations','intercompanyTransactions','enterpriseAudit']::text[]));
create or replace function public.finora_guard_posted_source_records()
returns trigger language plpgsql set search_path=public as $$
declare vid text:=coalesce(old.data->>'journalVoucherId',''); voucher_status text:=''; source_locked boolean:=false;
begin
 if old.collection not in ('invoices','purchases','payments','expenses','cheques','contractStatements','payrollRuns','employeeBenefitAccruals','pettyCashTransactions') then return case when tg_op='DELETE' then old else new end; end if;
 if vid<>'' then select coalesce(r.data->>'status','') into voucher_status from public.records r where r.owner_id=old.owner_id and r.collection='journalVouchers' and r.id=vid; end if;
 source_locked:=coalesce(old.data->>'accountingStatus','')='posted' or (old.collection='cheques' and coalesce(old.data->>'status','') in ('cleared','bounced','cancelled')) or (old.collection='contractStatements' and coalesce(old.data->>'status','') in ('posted','reversed')) or (old.collection in ('payrollRuns','employeeBenefitAccruals','pettyCashTransactions') and coalesce(old.data->>'status','') in ('posted','reversed')) or voucher_status in ('posted','reversed');
 if not source_locked then return case when tg_op='DELETE' then old else new end; end if;
 if tg_op='UPDATE' and new.data=old.data then return new; end if;
 raise exception 'source record linked to posted/reversed accounting history is immutable';
end $$;